### ISSUE TITLE
Does not work in VS Code 1.66.0

### ISSUE THREAD

**Issue by tasop-rsconnect** [prosser/json-schema-validation-extension#2]
I have the extension installed on OSX, VS Code 1.66.0.

It doesn't seem to activate at all. Extension host output shows this:

```
[2022-04-04 09:30:07.663] [exthost] [error] Activating extension prosser.json-schema-2020-validation failed due to an error:
[2022-04-04 09:30:07.663] [exthost] [error] Error: Cannot find module '/Users/***/.vscode/extensions/prosser.json-schema-2020-validation-0.0.5/out/extension'
```

The `out` directory doesn't exist.

**Comment by tasop-rsconnect** [comment]
If I create a symbolic link `out` -> `dist` in the extension's folder it can start, but then it can't execute `dist/server/osx-x64/JsonSchemaLanguageServer`.

This seems like an OSX issue, after the directory name issue was fixed.

**Comment by prosser** [comment]
Interesting. I don't have a Mac handy, but maybe this will repro on linux so I can fix it. Thanks for reporting!
